// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwtrdhnctzasddbeilwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dHJkaG5jdHphc2RkYmVpbHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njg2OTEsImV4cCI6MjA2OTA0NDY5MX0.KpfR54ZUuhe7wZ-yf1rZny0Rk1C17MlLssB-EjOymRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});